# Generated by Django 5.1.7 on 2025-03-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_player_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fullname",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="masterlevel",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="masterytitle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rookie", "Rookie"),
                    ("Warrior", "Warrior"),
                    ("Protagonist", "Protagonist"),
                    ("Diplomat", "Diplomat"),
                    ("Maverick", "Maverick"),
                    ("Prodigy", "Prodigy"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
