# Generated by Django 5.1.7 on 2025-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_player_fullname_player_masterlevel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="masterytitle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rookie", "Rookie"),
                    ("Warrior", "Warrior"),
                    ("Protagonist", "Protagonist"),
                    ("Diplomat", "Diplomat"),
                    ("Maverick", "Maverick"),
                    ("Prodigy", "Prodigy"),
                ],
                default="Rookie",
                max_length=150,
                null=True,
            ),
        ),
    ]
