# Generated by Django 5.1.7 on 2025-03-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_player_masterytitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="primary_accent_color",
            field=models.CharField(default="#555555", max_length=7),
        ),
        migrations.AddField(
            model_name="player",
            name="secondary_accent_color",
            field=models.CharField(default="#aaaaaa", max_length=7),
        ),
    ]
