# Generated by Django 5.1.7 on 2025-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_player_primary_accent_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="streak_count",
            field=models.IntegerField(default=0),
        ),
    ]
