# Generated by Django 5.1.7 on 2025-03-11 13:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_player_streak_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="level",
            new_name="lifelevel",
        ),
        migrations.RemoveField(
            model_name="player",
            name="masterlevel",
        ),
        migrations.RemoveField(
            model_name="player",
            name="xp",
        ),
        migrations.AddField(
            model_name="player",
            name="categorylevels",
            field=models.JSONField(default=users.models.Player.default_category_levels),
        ),
        migrations.AddField(
            model_name="player",
            name="categoryxp",
            field=models.JSONField(default=users.models.Player.default_xp),
        ),
    ]
