# Generated by Django 5.1.7 on 2025-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_level_player_lifelevel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="masterlevel",
            field=models.IntegerField(default=1),
        ),
    ]
