# Generated by Django 5.1.7 on 2025-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_player_masterlevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="totalxp",
            field=models.IntegerField(default=0),
        ),
    ]
