# Generated by Django 5.1.7 on 2025-03-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_image_post_post_image_alter_post_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
