# Generated by Django 5.1.7 on 2025-03-26 12:22

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_player_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="Screenshot_2025-03-25_at_10.40.01_PM_vugdxk",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("Private", "Private"), ("Public", "Public")],
                        default="Public",
                        max_length=10,
                    ),
                ),
                (
                    "notifications",
                    models.CharField(
                        choices=[("On", "On"), ("Off", "Off")],
                        default="On",
                        max_length=3,
                    ),
                ),
                (
                    "appearance",
                    models.CharField(
                        choices=[("Light", "Light"), ("Dark", "Dark")],
                        default="Light",
                        max_length=10,
                    ),
                ),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="users.player",
                    ),
                ),
            ],
        ),
    ]
