# Generated by Django 5.1.7 on 2025-03-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_player_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="user",
        ),
    ]
