# Generated by Django 5.1.7 on 2025-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_player_profile_picture_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_visit",
            field=models.DateField(blank=True, null=True),
        ),
    ]
