# Generated by Django 5.1.7 on 2025-03-26 01:45

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="joined_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="player",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="Screenshot_2025-03-25_at_10.40.01_PM_vugdxk",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
