# Generated by Django 5.1.7 on 2025-03-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_player_last_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="users.player"
            ),
        ),
    ]
