# Generated by Django 5.1.7 on 2025-03-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="button_primary_accent_color",
            field=models.CharField(default="#1981ea", max_length=7),
        ),
        migrations.AddField(
            model_name="player",
            name="button_secondary_accent_color",
            field=models.CharField(default="#1981ea", max_length=7),
        ),
    ]
