# Generated by Django 5.1.7 on 2025-03-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_player_button_primary_accent_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="button_primary_accent_color",
        ),
        migrations.RemoveField(
            model_name="player",
            name="button_secondary_accent_color",
        ),
    ]
