# Generated by Django 5.1.7 on 2025-03-25 12:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dfohn9dcz/image/upload/v1742902918/Screenshot_2025-03-25_at_10.40.01_PM_vugdxk.png",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
