# Generated by Django 5.1.7 on 2025-03-26 01:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
