# Generated by Django 5.1.7 on 2025-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_activity_desc_activitylog_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="post",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
