# Generated by Django 5.1.7 on 2025-03-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_activitylog_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="total_time_done",
        ),
    ]
