# Generated by Django 5.1.7 on 2025-03-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_activitylog_total_time_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="main.post",
            ),
            preserve_default=False,
        ),
    ]
